plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.clip'
version = '0.0.1-SNAPSHOT'

bootJar{enabled = false}
jar{enabled = true}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'software.amazon.awssdk:s3:2.31.16'
    implementation 'org.springframework:spring-context'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.google.firebase:firebase-admin:9.4.3'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-tx'
}

tasks.named('test') {
    useJUnitPlatform()
}
