version: "3.9"

services:

  office-api-server:
    image: ${OFFICE_API_IMAGE_URI}
    container_name: ${OFFICE_CONTAINER_NAME}
    environment:
      spring.datasource.url: ${URL}
      spring.datasource.username: ${USERNAME}
      spring.datasource.password: ${PASSWORD}
      spring.datasource.redis.host: ${REDIS_HOST}
      spring.datasource.redis.port: ${REDIS_PORT}
      jwt.secret-key: ${JWT_KEY}
      cloud.aws.credentials.access-key: ${S3_ACCESS_KEY}
      cloud.aws.credentials.secret-key: ${S3_SECRET_KEY}
      cloud.aws.s3.bucket: ${S3_BUCKET_NAME}
      toss.secret-key: ${TOSS_KEY}
      cloud.aws.s3.fcm.sdk: ${FCM_SDK}
      user.timezone: Asia/Seoul
    ports:
      - "8080:8080"
    networks:
      - office

networks:
  office:
    driver: bridge