spring:
  profiles:
    include:
    - office-data
    - core-date
    - infra

  datasource:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
    login:
      max-fail-count: 10
      block-duration-seconds: 3600 # 1 시간
