spring:
  profiles:
    include:
    - office-data
    - core-date
    - infra

  datasource:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    login:
      max-fail-count: 10
      block-duration-seconds: 3600 # 1 시간

toss:
  secret-key: ${TOSS_KEY}