name: Deploy Common

on:
  push:
    branches:
      - develop

jobs:
  deploy-Admin:
    uses: ./.github/workflows/CD-office.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_HOST: ${{ secrets.EC2_OFFICE_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_OFFICE_KEY }}
      AWS_REGION: ap-northeast-2

  deploy-Api:
    uses: ./.github/workflows/CD-api.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_HOST: ${{ secrets.EC2_API_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_API_KEY }}
      AWS_REGION: ap-northeast-2


