name: Deploy office module

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      EC2_HOST:
        required: true
      EC2_USER:
        required: true
      EC2_KEY:
        required: true

jobs:
  build:
    uses: ./.github/workflows/gradle_build.yml
    with:
      project-name: office
      workflow-id: ${{ github.run_id }}

  push-image:
    needs: build
    uses: ./.github/workflows/ec2_push.yml
    with:
      project-name: office
      docker-file-path: ./boot/office/Dockerfile
      host-port: 8081
      ecr-repository: 442042528525.dkr.ecr.ap-northeast-2.amazonaws.com/clibi/office
      ecr-repository-name: clibi/office
      secret-manager: arn:aws:secretsmanager:ap-northeast-2:442042528525:secret:dev/clibi/rds-eCWfXL
      container-name: office-server
      workflow-id: ${{ github.run_id }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}